# Generated by Django 5.2.4 on 2025-08-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileModels',
            new_name='ProfileModel',
        ),
    ]
