# Generated by Django 5.2 on 2025-08-03 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_rename_profilemodels_profilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='university',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(blank=True, max_length=4, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='pdf.profilemodel')),
            ],
            options={
                'ordering': ['order', 'graduation_year'],
            },
        ),
    ]
